//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beauty_salon.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
        public Nullable<int> ServiceId { get; set; }
        public Nullable<int> ClientId { get; set; }
        public Nullable<int> MasterId { get; set; }
        public Nullable<bool> Confirmation { get; set; }
        public Nullable<int> FeedbackId { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Feedback Feedback { get; set; }
        public virtual Service Service { get; set; }
    }
}
